# How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

def FindDistinctPowers():
	setS = set()

	for i in range(2, 101):
		for j in range(2, 101):
			setS.add(i ** j)

	print(len(setS))
	# There is a far more efficient way to do this, but for this problem
	# the above method works just fine.
	return len(setS)

FindDistinctPowers()

# Returns 9183